context:
  name: libfranka
  version: "0.15.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/frankarobotics/libfranka/archive/refs/tags/0.15.0.tar.gz
    sha256: 32044d467688cc091f047a8ef52825b2842d34f52030a4cedbe99e4a51b6ab3a

  # Exact commit hash was obtained from the submodule inside the target libfranka version
  - url: https://github.com/frankarobotics/libfranka-common/archive/cd38d0ec300b7e6864407d85d1e88e2fba31ccd5.tar.gz
    sha256: 0696297f235dc63c014232acde602aa9ad59bf8630d5b9901b32ac79f4d2dee2
    target_directory: common



build:
  skip:
    - win
    - osx
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
    - ninja
  host:
    - eigen
    - poco
    - pinocchio
    - fmt
  run_exports:
    - ${{ pin_subpackage('libfranka', upper_bound='x.x.x') }}

tests:
  - package_contents:
      lib:
        - franka

about:
  homepage: https://github.com/frankarobotics/libfranka
  summary: 'C++ client library to control Franka robots in real-time'
  description: |
    libfranka is a C++ library that provides low-level control of Franka
    Robotics research robots. The generated API documentation offers
    an overview of its capabilities, while the Franka Control Interface (FCI)
    documentation provides more information on setting up the robot
    and utilizing its features and functionalities.
  license: Apache-2.0
  license_file:
    - LICENSE
    - common/LICENSE
  documentation: https://frankarobotics.github.io/docs/libfranka.html
  repository: https://github.com/frankarobotics/libfranka

extra:
  recipe-maintainers:
    - nmarticorena
