context:
  name: libfranka
  version: "0.21.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/frankarobotics/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
    sha256: 737dde350958c9d9dadf7b1a34e18373f580066a436ab90a49c9717e65fb0795

  # Exact commit hash was obtained from the submodule inside the target libfranka version
  - url: https://github.com/frankarobotics/libfranka-common/archive/2e090a65e51c94a98f9fc82b6ec3d1aa54d0f85f.tar.gz
    sha256: 25a9d7f1203f7452425f266551b47d30ce043a408feee280403dd7d56d6d6772
    target_directory: common



build:
  skip:
    - win
    - osx
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
    - ninja
  host:
    - eigen
    - eigen-abi-devel
    - poco
    - pinocchio
    - fmt
  run_exports:
    - ${{ pin_subpackage('libfranka', upper_bound='x.x.x') }}

tests:
  - package_contents:
      lib:
        - franka

about:
  homepage: https://github.com/frankarobotics/libfranka
  summary: 'C++ client library to control Franka robots in real-time'
  description: |
    libfranka is a C++ library that provides low-level control of Franka
    Robotics research robots. The generated API documentation offers
    an overview of its capabilities, while the Franka Control Interface (FCI)
    documentation provides more information on setting up the robot
    and utilizing its features and functionalities.
  license: Apache-2.0
  license_file:
    - LICENSE
    - common/LICENSE
  documentation: https://frankarobotics.github.io/docs/libfranka.html
  repository: https://github.com/frankarobotics/libfranka

extra:
  recipe-maintainers:
    - nmarticorena
