conda_build_tool: rattler-build
bot:
  abi_migration_branches:
  - v0.9.2
  - v0.15.0
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
